      - name: Build Amazon APK
        working-directory: ./frontend
        run: |
          npx expo prebuild
          eas build --platform android --profile production --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          AMAZON_CLIENT_ID: ${{ secrets.AMAZON_CLIENT_ID }}
          AMAZON_CLIENT_SECRET: ${{ secrets.AMAZON_CLIENT_SECRET }}
          
          
