name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: build
        run: |
          npm install
          rm -f tsconfig.json
          echo '{"compilerOptions":{"target":"ESNext","module":"ESNext","moduleResolution":"node","jsx":"react-jsx","strict":true}}' > tsconfig.json
          npm run build
          
