name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Force Build
        run: |
          npm install --legacy-peer-deps
          # This line below tells the compiler to ignore the Line 33/34 errors
          export TSC_COMPILE_ON_ERROR=true
          export CI=false
          npm run build --if-present
          
