name: EAS APK Build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN_GIT }}

      - name: Install dependencies
        run: npm ci

      - name: Build Standalone APK
        run: eas build --platform android --profile apk --non-interactive
        
